// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajistcufqrcyruwjvxse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqaXN0Y3VmcXJjeXJ1d2p2eHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODE3MDUsImV4cCI6MjA2NTk1NzcwNX0.h0gt_wOuSO0QSh9LyKajubakC43Jaa47j5BAzLAu4Lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);